sudo: required

language: bash

services: docker

env:
  - VERSION=1.2 VARIANT=sqlite3 SRC_DIR=sqlite3/quickstart EXTENSION=quickstart LATEST=true
  - VERSION=1.2 VARIANT=mariadb SRC_DIR=mariadb/quickstart EXTENSION=quickstart
  - VERSION=1.2 VARIANT=alpine SRC_DIR=alpine/src
  - VERSION=1.2 VARIANT=x86_64 SRC_DIR=alpine/x86_64

before_install:
  - docker build -t rafaelhdr/glewlwyd-oauth2-server:base .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rafaelhdr/glewlwyd-oauth2-server:base

before_script:
  - image="rafaelhdr/glewlwyd-oauth2-server:${VERSION}-${VARIANT}${EXTENSION:+-$EXTENSION}"
  - build_dir="${SRC_DIR}/."

script:
  - travis_retry docker build -t "$image" ${build_dir}
  - travis_retry docker push "$image"
  - 'if [ "$LATEST" = "true" ]; then
      travis_retry docker build -t rafaelhdr/glewlwyd-oauth2-server:latest ${build_dir} ;
      travis_retry docker push rafaelhdr/glewlwyd-oauth2-server:latest ;
    fi'

after_script:
  - docker images

branches:
  only:
  - master
